#!/bin/bash
#SBATCH --job-name="MPI output"
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=1
#SBATCH --time=05:00
#SBATCH --mem-per-cpu=4G
#SBATCH --output=mpi_out.out

module load OpenMPI
module load Info0939Tools

mpicc fdtd_mpi.c -o bin/fdtd_mpi -lm
cd ./example_inputs/simple3d
srun ../../bin/fdtd_mpi param_3d.txt
rm cuty.msh
rm cutx.msh
rm cutz.msh
data2gmsh -cuty 0.5 out_p.dat 
data2gmsh -cutz 0.4 out_p.dat 
data2gmsh -cutx 0.6 out_p.dat 
cd ../..