#!/bin/bash
#SBATCH --job-name="OPENMP MPI output"
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=8G
#SBATCH --time=15:00
#SBATCH --output=out/openmp_mpi_out.out

module load OpenMPI
module load Info0939Tools

mpicc -fopenmp MPI_OPENMP/fdtd_mpi_openmp.c -o bin/fdtd_mpi_openmp -lm -O3
cd ./example_inputs/slit

export OMP_NUM_THREADS=4
export OMP_PROC_BIND=spread

srun ../../bin/fdtd_mpi_openmp param_slit_1x.txt
data2gmsh out_slit_1x_pz_025.dat