#!/bin/bash
#SBATCH --job-name="OPENMP MPI output"
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8G
#SBATCH --time=20:00
#SBATCH --output=out/openmp_mpi_out.out

module load OpenMPI
module load Info0939Tools

mpicc MPI_OPENMP/fdtd_mpi_openmp.c -o bin/fdtd_mpi_openmp -lm -O3 -fopenmp
cd ./example_inputs/simple3d

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ../../bin/fdtd_mpi_openmp param_3d.txt

rm cutx.msh
data2gmsh -cutx 0.5 out_p.dat 
cd ../..