#!/bin/bash
#SBATCH --job-name="OPENMP output"
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=4G
#SBATCH --time=10:00
#SBATCH --output=./openmp_out.out

module load Info0939Tools

gcc -fopenmp OPENMP/fdtd_openmp.c -o bin/fdtd_openmp -lm -O3
cd ./example_inputs/slit/simple3d_4x


export OMP_NUM_THREADS=4
export OMP_PROC_BIND=spread

srun ../../../bin/fdtd_openmp param_simple_4x.txt
data2gmsh out_simple_4x_pz_05.dat
