#!/bin/bash
#SBATCH --job-name="OPENMP output"
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=4G
#SBATCH --time=10:00
#SBATCH --output=out/openmp_out.out

module load Info0939Tools

gcc  -fopenmp OPENMP/fdtd_openmp.c -o bin/fdtd_openmp -lm -O3
cd ./example_inputs/simple3d

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

./../../bin/fdtd_openmp param_3d.txt

rm cutx.msh
data2gmsh -cutx 0.5 out_p.dat 
cd ../..